### ISSUE TITLE
V2 fatal error

### ISSUE THREAD

**Issue by eimantaaas** [aglipanci/laravel-dashboard-forge-tile#4]
Hey,

recently we have updated to use v2, but then running artisan commands it throws fatal:

`In ForgeTileServiceProvider.php line 37:`
`Class 'Themsaid\Forge\Forge' not found`

Changing namespace from `Themsaid\Forge\Forge` to `Laravel\Forge\Forge` fixes fatal error

**Comment by aglipanci** [comment]
@eimantaaas can you update to 2.2.0? It should be fixed now.
